import "./globals.css";
import { Geist_Mono } from "next/font/google";

export const metadata = {
  title: "Mood Journal",
  description: "Generated by create next app",
};

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
