import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Mood Journal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

[
  {
    id: 1745328328992,
    date: "2025-04-21T13:25:28.992Z",
    mood: { id: "angry", emoji: "😠", label: "Angry", color: "bg-red-300" },
    note: "advs",
    weather: { temp: 23, condition: "Clear", icon: "☀️" },
    created: "2025-04-21T13:25:28.992Z",
    lastUpdated: "2025-04-21T13:27:35.933Z",
  },
];
